/**
 * @deprecated — Prices are now generated by the local simulation engine (priceEngine.ts).
 * This route is no longer called by any client. Kept for reference only.
 */
import { NextRequest, NextResponse } from "next/server";

// Map our symbols to CoinGecko IDs
const COINGECKO_IDS: Record<string, string> = {
  "BTC": "bitcoin",
  "ETH": "ethereum",
  "XRP": "ripple",
  "BNB": "binancecoin",
  "SOL": "solana",
  "ADA": "cardano",
  "DOGE": "dogecoin",
  "DOT": "polkadot",
  "MATIC": "matic-network",
  "LTC": "litecoin",
  "LINK": "chainlink",
  "AVAX": "avalanche-2",
  "UNI":  "uniswap",
  "ATOM": "cosmos",
  "XLM":  "stellar",
};

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<Record<string, string>> }
) {
  try {
    const { symbol } = await params;
    const base = symbol.toUpperCase().replace("/USD","").replace("USD","");
    const cgId = COINGECKO_IDS[base];

    if (!cgId) {
      return NextResponse.json({ error: `Unknown symbol: ${symbol}` }, { status: 400 });
    }

    const url = `https://api.coingecko.com/api/v3/simple/price?ids=${cgId}&vs_currencies=usd&include_24hr_change=true&include_24hr_vol=true&include_market_cap=true`;
    const res  = await fetch(url, {
      headers: { Accept: "application/json" },
      next:    { revalidate: 5 }, // cache 5 seconds
    });

    if (!res.ok) throw new Error("CoinGecko API error");

    const data = await res.json();
    const coin = data[cgId];
    if (!coin) throw new Error("No data returned");

    return NextResponse.json({
      symbol:    `${base}/USD`,
      price:     coin.usd,
      change24h: coin.usd_24h_change ?? 0,
      volume24h: coin.usd_24h_vol    ?? 0,
      marketCap: coin.usd_market_cap ?? 0,
      updatedAt: new Date().toISOString(),
    });
  } catch (err) {
    return NextResponse.json({ error: "Failed to fetch price" }, { status: 500 });
  }
}
